// Generated offline bundle. qualia_info.json is the only maintained data source.
import fs from 'node:fs';
const root = new URL('../', import.meta.url);
const seed = JSON.parse(fs.readFileSync(new URL('qualia_info.json', root), 'utf8'));
const output = `// GENERATED by node tools/sync-seed.mjs. Edit qualia_info.json instead.\n'use strict';\nglobalThis.QUALITHM_SEED = ${JSON.stringify(seed, null, 2)};\n`;
const target = new URL('seed-fallback.js', root);
if (process.argv.includes('--check')) {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) throw new Error('Seed fallback is stale; run node tools/sync-seed.mjs');
  console.log('seed-fallback: synchronized');
} else { fs.writeFileSync(target, output); console.log('seed-fallback: generated'); }
